/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTillsRouteImport } from './routes/_app/tills'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppQrRouteImport } from './routes/_app/qr'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppOrgsRouteImport } from './routes/_app/orgs'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppDiscountsRouteImport } from './routes/_app/discounts'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppMenuRouteRouteImport } from './routes/_app/menu/route'
import { Route as AppInventoryRouteRouteImport } from './routes/_app/inventory/route'
import { Route as AppDeliveryRouteRouteImport } from './routes/_app/delivery/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppMenuIndexRouteImport } from './routes/_app/menu/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppDeliveryIndexRouteImport } from './routes/_app/delivery/index'
import { Route as AppSettingsWhatsappRouteImport } from './routes/_app/settings/whatsapp'
import { Route as AppSettingsPaymentMethodsRouteImport } from './routes/_app/settings/payment-methods'
import { Route as AppMenuRecipesRouteImport } from './routes/_app/menu/recipes'
import { Route as AppMenuOverridesRouteImport } from './routes/_app/menu/overrides'
import { Route as AppMenuItemsRouteImport } from './routes/_app/menu/items'
import { Route as AppMenuEngineeringRouteImport } from './routes/_app/menu/engineering'
import { Route as AppMenuBundlesRouteImport } from './routes/_app/menu/bundles'
import { Route as AppMenuAdvisorRouteImport } from './routes/_app/menu/advisor'
import { Route as AppKitchenStationsRouteImport } from './routes/_app/kitchen/stations'
import { Route as AppKitchenRoutingRouteImport } from './routes/_app/kitchen/routing'
import { Route as AppInventoryWasteRouteImport } from './routes/_app/inventory/waste'
import { Route as AppInventoryTransfersRouteImport } from './routes/_app/inventory/transfers'
import { Route as AppInventoryTodayRouteImport } from './routes/_app/inventory/today'
import { Route as AppInventorySettingsRouteImport } from './routes/_app/inventory/settings'
import { Route as AppInventoryReportsRouteImport } from './routes/_app/inventory/reports'
import { Route as AppInventoryPurchasingRouteImport } from './routes/_app/inventory/purchasing'
import { Route as AppInventoryItemsRouteImport } from './routes/_app/inventory/items'
import { Route as AppInventoryCountsRouteImport } from './routes/_app/inventory/counts'
import { Route as AppDeliveryZonesRouteImport } from './routes/_app/delivery/zones'
import { Route as AppDeliverySettingsRouteImport } from './routes/_app/delivery/settings'
import { Route as AppDeliveryChannelsRouteImport } from './routes/_app/delivery/channels'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTillsRoute = AppTillsRouteImport.update({
  id: '/tills',
  path: '/tills',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscountsRoute = AppDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMenuRouteRoute = AppMenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRouteRoute = AppInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeliveryRouteRoute = AppDeliveryRouteRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppDeliveryIndexRoute = AppDeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeliveryRouteRoute,
} as any)
const AppSettingsWhatsappRoute = AppSettingsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPaymentMethodsRoute =
  AppSettingsPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppMenuRecipesRoute = AppMenuRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppMenuOverridesRoute = AppMenuOverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppMenuItemsRoute = AppMenuItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppMenuEngineeringRoute = AppMenuEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppMenuBundlesRoute = AppMenuBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppMenuAdvisorRoute = AppMenuAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppMenuRouteRoute,
} as any)
const AppKitchenStationsRoute = AppKitchenStationsRouteImport.update({
  id: '/kitchen/stations',
  path: '/kitchen/stations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKitchenRoutingRoute = AppKitchenRoutingRouteImport.update({
  id: '/kitchen/routing',
  path: '/kitchen/routing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryWasteRoute = AppInventoryWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryTransfersRoute = AppInventoryTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryTodayRoute = AppInventoryTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventorySettingsRoute = AppInventorySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryReportsRoute = AppInventoryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryPurchasingRoute = AppInventoryPurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryItemsRoute = AppInventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppInventoryCountsRoute = AppInventoryCountsRouteImport.update({
  id: '/counts',
  path: '/counts',
  getParentRoute: () => AppInventoryRouteRoute,
} as any)
const AppDeliveryZonesRoute = AppDeliveryZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppDeliveryRouteRoute,
} as any)
const AppDeliverySettingsRoute = AppDeliverySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDeliveryRouteRoute,
} as any)
const AppDeliveryChannelsRoute = AppDeliveryChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppDeliveryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/delivery': typeof AppDeliveryRouteRouteWithChildren
  '/inventory': typeof AppInventoryRouteRouteWithChildren
  '/menu': typeof AppMenuRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/branches': typeof AppBranchesRoute
  '/discounts': typeof AppDiscountsRoute
  '/orders': typeof AppOrdersRoute
  '/orgs': typeof AppOrgsRoute
  '/permissions': typeof AppPermissionsRoute
  '/qr': typeof AppQrRoute
  '/reservations': typeof AppReservationsRoute
  '/shifts': typeof AppShiftsRoute
  '/tills': typeof AppTillsRoute
  '/users': typeof AppUsersRoute
  '/delivery/channels': typeof AppDeliveryChannelsRoute
  '/delivery/settings': typeof AppDeliverySettingsRoute
  '/delivery/zones': typeof AppDeliveryZonesRoute
  '/inventory/counts': typeof AppInventoryCountsRoute
  '/inventory/items': typeof AppInventoryItemsRoute
  '/inventory/purchasing': typeof AppInventoryPurchasingRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/settings': typeof AppInventorySettingsRoute
  '/inventory/today': typeof AppInventoryTodayRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/inventory/waste': typeof AppInventoryWasteRoute
  '/kitchen/routing': typeof AppKitchenRoutingRoute
  '/kitchen/stations': typeof AppKitchenStationsRoute
  '/menu/advisor': typeof AppMenuAdvisorRoute
  '/menu/bundles': typeof AppMenuBundlesRoute
  '/menu/engineering': typeof AppMenuEngineeringRoute
  '/menu/items': typeof AppMenuItemsRoute
  '/menu/overrides': typeof AppMenuOverridesRoute
  '/menu/recipes': typeof AppMenuRecipesRoute
  '/settings/payment-methods': typeof AppSettingsPaymentMethodsRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/delivery/': typeof AppDeliveryIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/menu/': typeof AppMenuIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/branches': typeof AppBranchesRoute
  '/discounts': typeof AppDiscountsRoute
  '/orders': typeof AppOrdersRoute
  '/orgs': typeof AppOrgsRoute
  '/permissions': typeof AppPermissionsRoute
  '/qr': typeof AppQrRoute
  '/reservations': typeof AppReservationsRoute
  '/shifts': typeof AppShiftsRoute
  '/tills': typeof AppTillsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/delivery/channels': typeof AppDeliveryChannelsRoute
  '/delivery/settings': typeof AppDeliverySettingsRoute
  '/delivery/zones': typeof AppDeliveryZonesRoute
  '/inventory/counts': typeof AppInventoryCountsRoute
  '/inventory/items': typeof AppInventoryItemsRoute
  '/inventory/purchasing': typeof AppInventoryPurchasingRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/settings': typeof AppInventorySettingsRoute
  '/inventory/today': typeof AppInventoryTodayRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/inventory/waste': typeof AppInventoryWasteRoute
  '/kitchen/routing': typeof AppKitchenRoutingRoute
  '/kitchen/stations': typeof AppKitchenStationsRoute
  '/menu/advisor': typeof AppMenuAdvisorRoute
  '/menu/bundles': typeof AppMenuBundlesRoute
  '/menu/engineering': typeof AppMenuEngineeringRoute
  '/menu/items': typeof AppMenuItemsRoute
  '/menu/overrides': typeof AppMenuOverridesRoute
  '/menu/recipes': typeof AppMenuRecipesRoute
  '/settings/payment-methods': typeof AppSettingsPaymentMethodsRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/delivery': typeof AppDeliveryIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/menu': typeof AppMenuIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/delivery': typeof AppDeliveryRouteRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteRouteWithChildren
  '/_app/menu': typeof AppMenuRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/discounts': typeof AppDiscountsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/orgs': typeof AppOrgsRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/qr': typeof AppQrRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/tills': typeof AppTillsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/delivery/channels': typeof AppDeliveryChannelsRoute
  '/_app/delivery/settings': typeof AppDeliverySettingsRoute
  '/_app/delivery/zones': typeof AppDeliveryZonesRoute
  '/_app/inventory/counts': typeof AppInventoryCountsRoute
  '/_app/inventory/items': typeof AppInventoryItemsRoute
  '/_app/inventory/purchasing': typeof AppInventoryPurchasingRoute
  '/_app/inventory/reports': typeof AppInventoryReportsRoute
  '/_app/inventory/settings': typeof AppInventorySettingsRoute
  '/_app/inventory/today': typeof AppInventoryTodayRoute
  '/_app/inventory/transfers': typeof AppInventoryTransfersRoute
  '/_app/inventory/waste': typeof AppInventoryWasteRoute
  '/_app/kitchen/routing': typeof AppKitchenRoutingRoute
  '/_app/kitchen/stations': typeof AppKitchenStationsRoute
  '/_app/menu/advisor': typeof AppMenuAdvisorRoute
  '/_app/menu/bundles': typeof AppMenuBundlesRoute
  '/_app/menu/engineering': typeof AppMenuEngineeringRoute
  '/_app/menu/items': typeof AppMenuItemsRoute
  '/_app/menu/overrides': typeof AppMenuOverridesRoute
  '/_app/menu/recipes': typeof AppMenuRecipesRoute
  '/_app/settings/payment-methods': typeof AppSettingsPaymentMethodsRoute
  '/_app/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/_app/delivery/': typeof AppDeliveryIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/delivery'
    | '/inventory'
    | '/menu'
    | '/settings'
    | '/analytics'
    | '/branches'
    | '/discounts'
    | '/orders'
    | '/orgs'
    | '/permissions'
    | '/qr'
    | '/reservations'
    | '/shifts'
    | '/tills'
    | '/users'
    | '/delivery/channels'
    | '/delivery/settings'
    | '/delivery/zones'
    | '/inventory/counts'
    | '/inventory/items'
    | '/inventory/purchasing'
    | '/inventory/reports'
    | '/inventory/settings'
    | '/inventory/today'
    | '/inventory/transfers'
    | '/inventory/waste'
    | '/kitchen/routing'
    | '/kitchen/stations'
    | '/menu/advisor'
    | '/menu/bundles'
    | '/menu/engineering'
    | '/menu/items'
    | '/menu/overrides'
    | '/menu/recipes'
    | '/settings/payment-methods'
    | '/settings/whatsapp'
    | '/delivery/'
    | '/inventory/'
    | '/menu/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/branches'
    | '/discounts'
    | '/orders'
    | '/orgs'
    | '/permissions'
    | '/qr'
    | '/reservations'
    | '/shifts'
    | '/tills'
    | '/users'
    | '/'
    | '/delivery/channels'
    | '/delivery/settings'
    | '/delivery/zones'
    | '/inventory/counts'
    | '/inventory/items'
    | '/inventory/purchasing'
    | '/inventory/reports'
    | '/inventory/settings'
    | '/inventory/today'
    | '/inventory/transfers'
    | '/inventory/waste'
    | '/kitchen/routing'
    | '/kitchen/stations'
    | '/menu/advisor'
    | '/menu/bundles'
    | '/menu/engineering'
    | '/menu/items'
    | '/menu/overrides'
    | '/menu/recipes'
    | '/settings/payment-methods'
    | '/settings/whatsapp'
    | '/delivery'
    | '/inventory'
    | '/menu'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/delivery'
    | '/_app/inventory'
    | '/_app/menu'
    | '/_app/settings'
    | '/_app/analytics'
    | '/_app/branches'
    | '/_app/discounts'
    | '/_app/orders'
    | '/_app/orgs'
    | '/_app/permissions'
    | '/_app/qr'
    | '/_app/reservations'
    | '/_app/shifts'
    | '/_app/tills'
    | '/_app/users'
    | '/_app/'
    | '/_app/delivery/channels'
    | '/_app/delivery/settings'
    | '/_app/delivery/zones'
    | '/_app/inventory/counts'
    | '/_app/inventory/items'
    | '/_app/inventory/purchasing'
    | '/_app/inventory/reports'
    | '/_app/inventory/settings'
    | '/_app/inventory/today'
    | '/_app/inventory/transfers'
    | '/_app/inventory/waste'
    | '/_app/kitchen/routing'
    | '/_app/kitchen/stations'
    | '/_app/menu/advisor'
    | '/_app/menu/bundles'
    | '/_app/menu/engineering'
    | '/_app/menu/items'
    | '/_app/menu/overrides'
    | '/_app/menu/recipes'
    | '/_app/settings/payment-methods'
    | '/_app/settings/whatsapp'
    | '/_app/delivery/'
    | '/_app/inventory/'
    | '/_app/menu/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tills': {
      id: '/_app/tills'
      path: '/tills'
      fullPath: '/tills'
      preLoaderRoute: typeof AppTillsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/qr': {
      id: '/_app/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discounts': {
      id: '/_app/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/delivery': {
      id: '/_app/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AppDeliveryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/delivery/': {
      id: '/_app/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof AppDeliveryIndexRouteImport
      parentRoute: typeof AppDeliveryRouteRoute
    }
    '/_app/settings/whatsapp': {
      id: '/_app/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AppSettingsWhatsappRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/payment-methods': {
      id: '/_app/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof AppSettingsPaymentMethodsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/menu/recipes': {
      id: '/_app/menu/recipes'
      path: '/recipes'
      fullPath: '/menu/recipes'
      preLoaderRoute: typeof AppMenuRecipesRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/menu/overrides': {
      id: '/_app/menu/overrides'
      path: '/overrides'
      fullPath: '/menu/overrides'
      preLoaderRoute: typeof AppMenuOverridesRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/menu/items': {
      id: '/_app/menu/items'
      path: '/items'
      fullPath: '/menu/items'
      preLoaderRoute: typeof AppMenuItemsRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/menu/engineering': {
      id: '/_app/menu/engineering'
      path: '/engineering'
      fullPath: '/menu/engineering'
      preLoaderRoute: typeof AppMenuEngineeringRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/menu/bundles': {
      id: '/_app/menu/bundles'
      path: '/bundles'
      fullPath: '/menu/bundles'
      preLoaderRoute: typeof AppMenuBundlesRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/menu/advisor': {
      id: '/_app/menu/advisor'
      path: '/advisor'
      fullPath: '/menu/advisor'
      preLoaderRoute: typeof AppMenuAdvisorRouteImport
      parentRoute: typeof AppMenuRouteRoute
    }
    '/_app/kitchen/stations': {
      id: '/_app/kitchen/stations'
      path: '/kitchen/stations'
      fullPath: '/kitchen/stations'
      preLoaderRoute: typeof AppKitchenStationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kitchen/routing': {
      id: '/_app/kitchen/routing'
      path: '/kitchen/routing'
      fullPath: '/kitchen/routing'
      preLoaderRoute: typeof AppKitchenRoutingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/waste': {
      id: '/_app/inventory/waste'
      path: '/waste'
      fullPath: '/inventory/waste'
      preLoaderRoute: typeof AppInventoryWasteRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/transfers': {
      id: '/_app/inventory/transfers'
      path: '/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AppInventoryTransfersRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/today': {
      id: '/_app/inventory/today'
      path: '/today'
      fullPath: '/inventory/today'
      preLoaderRoute: typeof AppInventoryTodayRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/settings': {
      id: '/_app/inventory/settings'
      path: '/settings'
      fullPath: '/inventory/settings'
      preLoaderRoute: typeof AppInventorySettingsRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/reports': {
      id: '/_app/inventory/reports'
      path: '/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof AppInventoryReportsRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/purchasing': {
      id: '/_app/inventory/purchasing'
      path: '/purchasing'
      fullPath: '/inventory/purchasing'
      preLoaderRoute: typeof AppInventoryPurchasingRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/items': {
      id: '/_app/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AppInventoryItemsRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/inventory/counts': {
      id: '/_app/inventory/counts'
      path: '/counts'
      fullPath: '/inventory/counts'
      preLoaderRoute: typeof AppInventoryCountsRouteImport
      parentRoute: typeof AppInventoryRouteRoute
    }
    '/_app/delivery/zones': {
      id: '/_app/delivery/zones'
      path: '/zones'
      fullPath: '/delivery/zones'
      preLoaderRoute: typeof AppDeliveryZonesRouteImport
      parentRoute: typeof AppDeliveryRouteRoute
    }
    '/_app/delivery/settings': {
      id: '/_app/delivery/settings'
      path: '/settings'
      fullPath: '/delivery/settings'
      preLoaderRoute: typeof AppDeliverySettingsRouteImport
      parentRoute: typeof AppDeliveryRouteRoute
    }
    '/_app/delivery/channels': {
      id: '/_app/delivery/channels'
      path: '/channels'
      fullPath: '/delivery/channels'
      preLoaderRoute: typeof AppDeliveryChannelsRouteImport
      parentRoute: typeof AppDeliveryRouteRoute
    }
  }
}

interface AppDeliveryRouteRouteChildren {
  AppDeliveryChannelsRoute: typeof AppDeliveryChannelsRoute
  AppDeliverySettingsRoute: typeof AppDeliverySettingsRoute
  AppDeliveryZonesRoute: typeof AppDeliveryZonesRoute
  AppDeliveryIndexRoute: typeof AppDeliveryIndexRoute
}

const AppDeliveryRouteRouteChildren: AppDeliveryRouteRouteChildren = {
  AppDeliveryChannelsRoute: AppDeliveryChannelsRoute,
  AppDeliverySettingsRoute: AppDeliverySettingsRoute,
  AppDeliveryZonesRoute: AppDeliveryZonesRoute,
  AppDeliveryIndexRoute: AppDeliveryIndexRoute,
}

const AppDeliveryRouteRouteWithChildren =
  AppDeliveryRouteRoute._addFileChildren(AppDeliveryRouteRouteChildren)

interface AppInventoryRouteRouteChildren {
  AppInventoryCountsRoute: typeof AppInventoryCountsRoute
  AppInventoryItemsRoute: typeof AppInventoryItemsRoute
  AppInventoryPurchasingRoute: typeof AppInventoryPurchasingRoute
  AppInventoryReportsRoute: typeof AppInventoryReportsRoute
  AppInventorySettingsRoute: typeof AppInventorySettingsRoute
  AppInventoryTodayRoute: typeof AppInventoryTodayRoute
  AppInventoryTransfersRoute: typeof AppInventoryTransfersRoute
  AppInventoryWasteRoute: typeof AppInventoryWasteRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteRouteChildren: AppInventoryRouteRouteChildren = {
  AppInventoryCountsRoute: AppInventoryCountsRoute,
  AppInventoryItemsRoute: AppInventoryItemsRoute,
  AppInventoryPurchasingRoute: AppInventoryPurchasingRoute,
  AppInventoryReportsRoute: AppInventoryReportsRoute,
  AppInventorySettingsRoute: AppInventorySettingsRoute,
  AppInventoryTodayRoute: AppInventoryTodayRoute,
  AppInventoryTransfersRoute: AppInventoryTransfersRoute,
  AppInventoryWasteRoute: AppInventoryWasteRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteRouteWithChildren =
  AppInventoryRouteRoute._addFileChildren(AppInventoryRouteRouteChildren)

interface AppMenuRouteRouteChildren {
  AppMenuAdvisorRoute: typeof AppMenuAdvisorRoute
  AppMenuBundlesRoute: typeof AppMenuBundlesRoute
  AppMenuEngineeringRoute: typeof AppMenuEngineeringRoute
  AppMenuItemsRoute: typeof AppMenuItemsRoute
  AppMenuOverridesRoute: typeof AppMenuOverridesRoute
  AppMenuRecipesRoute: typeof AppMenuRecipesRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
}

const AppMenuRouteRouteChildren: AppMenuRouteRouteChildren = {
  AppMenuAdvisorRoute: AppMenuAdvisorRoute,
  AppMenuBundlesRoute: AppMenuBundlesRoute,
  AppMenuEngineeringRoute: AppMenuEngineeringRoute,
  AppMenuItemsRoute: AppMenuItemsRoute,
  AppMenuOverridesRoute: AppMenuOverridesRoute,
  AppMenuRecipesRoute: AppMenuRecipesRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
}

const AppMenuRouteRouteWithChildren = AppMenuRouteRoute._addFileChildren(
  AppMenuRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsPaymentMethodsRoute: typeof AppSettingsPaymentMethodsRoute
  AppSettingsWhatsappRoute: typeof AppSettingsWhatsappRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsPaymentMethodsRoute: AppSettingsPaymentMethodsRoute,
  AppSettingsWhatsappRoute: AppSettingsWhatsappRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppDeliveryRouteRoute: typeof AppDeliveryRouteRouteWithChildren
  AppInventoryRouteRoute: typeof AppInventoryRouteRouteWithChildren
  AppMenuRouteRoute: typeof AppMenuRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppDiscountsRoute: typeof AppDiscountsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOrgsRoute: typeof AppOrgsRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppQrRoute: typeof AppQrRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppTillsRoute: typeof AppTillsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppKitchenRoutingRoute: typeof AppKitchenRoutingRoute
  AppKitchenStationsRoute: typeof AppKitchenStationsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDeliveryRouteRoute: AppDeliveryRouteRouteWithChildren,
  AppInventoryRouteRoute: AppInventoryRouteRouteWithChildren,
  AppMenuRouteRoute: AppMenuRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppDiscountsRoute: AppDiscountsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOrgsRoute: AppOrgsRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppQrRoute: AppQrRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppTillsRoute: AppTillsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppKitchenRoutingRoute: AppKitchenRoutingRoute,
  AppKitchenStationsRoute: AppKitchenStationsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
